version: "3.9"
services:

  db:
    image: mysql:latest
    container_name: db_bilemo
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
