version: "3.9"
services:

  db:
    image: mysql
    container_name: db_bilemo
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  www:
    build: php
    container_name: www_docker_bilemo
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

  networks:
    dev:

  volumes:
    db-data:
